version: '3.8'
services:
  frontend:
    container_name: frontend
    build: ./
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    command: npm start
