version: '3.3'
services:
  rest_api:
    hostname: rest_api
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: always
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app --worker-class=gevent --worker-connections=1 --workers=1 --threads=1 --timeout 600 --reload --access-logfile '-'
    volumes:
      - ../:/app/
