version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '5432:5432'
    volumes:
      - ../app-data/db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
